<?php
// All countries

$countries = array(
	'AF' => array('id' => 1,'phone_code' => 93,'country_name' => 'Afghanistan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'AFG'),
	'AX' => array('id' => 2,'phone_code' => 358,'country_name' => 'Aland Islands','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'ALA'),
	'AL' => array('id' => 3,'phone_code' => 355,'country_name' => 'Albania','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'ALB'),
	'DZ' => array('id' => 4,'phone_code' => 213,'country_name' => 'Algeria','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'DZA'),
	'AS' => array('id' => 5,'phone_code' => 1684,'country_name' => 'American Samoa','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'ASM'),
	'AD' => array('id' => 6,'phone_code' => 376,'country_name' => 'Andorra','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'AND'),
	'AO' => array('id' => 7,'phone_code' => 244,'country_name' => 'Angola','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'AGO'),
	'AI' => array('id' => 8,'phone_code' => 1264,'country_name' => 'Anguilla','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'AIA'),
	'AQ' => array('id' => 9,'phone_code' => 672,'country_name' => 'Antarctica','continent_code' => 'AN','continent_name' => 'Antarctica','alpha_3' => 'ATA'),
	'AG' => array('id' => 10,'phone_code' => 1268,'country_name' => 'Antigua and Barbuda','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'ATG'),
	'AR' => array('id' => 11,'phone_code' => 54,'country_name' => 'Argentina','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'ARG'),
	'AM' => array('id' => 12,'phone_code' => 374,'country_name' => 'Armenia','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'ARM'),
	'AW' => array('id' => 13,'phone_code' => 297,'country_name' => 'Aruba','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'ABW'),
	'AU' => array('id' => 14,'phone_code' => 61,'country_name' => 'Australia','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'AUS'),
	'AT' => array('id' => 15,'phone_code' => 43,'country_name' => 'Austria','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'AUT'),
	'AZ' => array('id' => 16,'phone_code' => 994,'country_name' => 'Azerbaijan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'AZE'),
	'BS' => array('id' => 17,'phone_code' => 1242,'country_name' => 'Bahamas','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'BHS'),
	'BH' => array('id' => 18,'phone_code' => 973,'country_name' => 'Bahrain','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'BHR'),
	'BD' => array('id' => 19,'phone_code' => 880,'country_name' => 'Bangladesh','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'BGD'),
	'BB' => array('id' => 20,'phone_code' => 1246,'country_name' => 'Barbados','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'BRB'),
	'BY' => array('id' => 21,'phone_code' => 375,'country_name' => 'Belarus','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'BLR'),
	'BE' => array('id' => 22,'phone_code' => 32,'country_name' => 'Belgium','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'BEL'),
	'BZ' => array('id' => 23,'phone_code' => 501,'country_name' => 'Belize','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'BLZ'),
	'BJ' => array('id' => 24,'phone_code' => 229,'country_name' => 'Benin','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'BEN'),
	'BM' => array('id' => 25,'phone_code' => 1441,'country_name' => 'Bermuda','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'BMU'),
	'BT' => array('id' => 26,'phone_code' => 975,'country_name' => 'Bhutan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'BTN'),
	'BO' => array('id' => 27,'phone_code' => 591,'country_name' => 'Bolivia','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'BOL'),
	'BQ' => array('id' => 28,'phone_code' => 599,'country_name' => 'Bonaire, Sint Eustatius and Saba','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'BES'),
	'BA' => array('id' => 29,'phone_code' => 387,'country_name' => 'Bosnia and Herzegovina','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'BIH'),
	'BW' => array('id' => 30,'phone_code' => 267,'country_name' => 'Botswana','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'BWA'),
	'BV' => array('id' => 31,'phone_code' => 55,'country_name' => 'Bouvet Island','continent_code' => 'AN','continent_name' => 'Antarctica','alpha_3' => 'BVT'),
	'BR' => array('id' => 32,'phone_code' => 55,'country_name' => 'Brazil','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'BRA'),
	'IO' => array('id' => 33,'phone_code' => 246,'country_name' => 'British Indian Ocean Territory','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'IOT'),
	'BN' => array('id' => 34,'phone_code' => 673,'country_name' => 'Brunei Darussalam','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'BRN'),
	'BG' => array('id' => 35,'phone_code' => 359,'country_name' => 'Bulgaria','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'BGR'),
	'BF' => array('id' => 36,'phone_code' => 226,'country_name' => 'Burkina Faso','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'BFA'),
	'BI' => array('id' => 37,'phone_code' => 257,'country_name' => 'Burundi','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'BDI'),
	'KH' => array('id' => 38,'phone_code' => 855,'country_name' => 'Cambodia','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'KHM'),
	'CM' => array('id' => 39,'phone_code' => 237,'country_name' => 'Cameroon','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'CMR'),
	'CA' => array('id' => 40,'phone_code' => 1,'country_name' => 'Canada','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'CAN'),
	'CV' => array('id' => 41,'phone_code' => 238,'country_name' => 'Cape Verde','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'CPV'),
	'KY' => array('id' => 42,'phone_code' => 1345,'country_name' => 'Cayman Islands','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'CYM'),
	'CF' => array('id' => 43,'phone_code' => 236,'country_name' => 'Central African Republic','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'CAF'),
	'TD' => array('id' => 44,'phone_code' => 235,'country_name' => 'Chad','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'TCD'),
	'CL' => array('id' => 45,'phone_code' => 56,'country_name' => 'Chile','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'CHL'),
	'CN' => array('id' => 46,'phone_code' => 86,'country_name' => 'China','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'CHN'),
	'CX' => array('id' => 47,'phone_code' => 61,'country_name' => 'Christmas Island','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'CXR'),
	'CC' => array('id' => 48,'phone_code' => 672,'country_name' => 'Cocos (Keeling) Islands','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'CCK'),
	'CO' => array('id' => 49,'phone_code' => 57,'country_name' => 'Colombia','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'COL'),
	'KM' => array('id' => 50,'phone_code' => 269,'country_name' => 'Comoros','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'COM'),
	'CG' => array('id' => 51,'phone_code' => 242,'country_name' => 'Congo','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'COG'),
	'CD' => array('id' => 52,'phone_code' => 242,'country_name' => 'Congo, Democratic Republic of the Congo','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'COD'),
	'CK' => array('id' => 53,'phone_code' => 682,'country_name' => 'Cook Islands','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'COK'),
	'CR' => array('id' => 54,'phone_code' => 506,'country_name' => 'Costa Rica','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'CRI'),
	'CI' => array('id' => 55,'phone_code' => 225,'country_name' => 'Cote D\'Ivoire','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'CIV'),
	'HR' => array('id' => 56,'phone_code' => 385,'country_name' => 'Croatia','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'HRV'),
	'CU' => array('id' => 57,'phone_code' => 53,'country_name' => 'Cuba','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'CUB'),
	'CW' => array('id' => 58,'phone_code' => 599,'country_name' => 'Curacao','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'CUW'),
	'CY' => array('id' => 59,'phone_code' => 357,'country_name' => 'Cyprus','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'CYP'),
	'CZ' => array('id' => 60,'phone_code' => 420,'country_name' => 'Czech Republic','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'CZE'),
	'DK' => array('id' => 61,'phone_code' => 45,'country_name' => 'Denmark','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'DNK'),
	'DJ' => array('id' => 62,'phone_code' => 253,'country_name' => 'Djibouti','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'DJI'),
	'DM' => array('id' => 63,'phone_code' => 1767,'country_name' => 'Dominica','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'DMA'),
	'DO' => array('id' => 64,'phone_code' => 1809,'country_name' => 'Dominican Republic','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'DOM'),
	'EC' => array('id' => 65,'phone_code' => 593,'country_name' => 'Ecuador','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'ECU'),
	'EG' => array('id' => 66,'phone_code' => 20,'country_name' => 'Egypt','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'EGY'),
	'SV' => array('id' => 67,'phone_code' => 503,'country_name' => 'El Salvador','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'SLV'),
	'GQ' => array('id' => 68,'phone_code' => 240,'country_name' => 'Equatorial Guinea','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'GNQ'),
	'ER' => array('id' => 69,'phone_code' => 291,'country_name' => 'Eritrea','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'ERI'),
	'EE' => array('id' => 70,'phone_code' => 372,'country_name' => 'Estonia','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'EST'),
	'ET' => array('id' => 71,'phone_code' => 251,'country_name' => 'Ethiopia','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'ETH'),
	'FK' => array('id' => 72,'phone_code' => 500,'country_name' => 'Falkland Islands (Malvinas)','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'FLK'),
	'FO' => array('id' => 73,'phone_code' => 298,'country_name' => 'Faroe Islands','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'FRO'),
	'FJ' => array('id' => 74,'phone_code' => 679,'country_name' => 'Fiji','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'FJI'),
	'FI' => array('id' => 75,'phone_code' => 358,'country_name' => 'Finland','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'FIN'),
	'FR' => array('id' => 76,'phone_code' => 33,'country_name' => 'France','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'FRA'),
	'GF' => array('id' => 77,'phone_code' => 594,'country_name' => 'French Guiana','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'GUF'),
	'PF' => array('id' => 78,'phone_code' => 689,'country_name' => 'French Polynesia','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'PYF'),
	'TF' => array('id' => 79,'phone_code' => 262,'country_name' => 'French Southern Territories','continent_code' => 'AN','continent_name' => 'Antarctica','alpha_3' => 'ATF'),
	'GA' => array('id' => 80,'phone_code' => 241,'country_name' => 'Gabon','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'GAB'),
	'GM' => array('id' => 81,'phone_code' => 220,'country_name' => 'Gambia','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'GMB'),
	'GE' => array('id' => 82,'phone_code' => 995,'country_name' => 'Georgia','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'GEO'),
	'DE' => array('id' => 83,'phone_code' => 49,'country_name' => 'Germany','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'DEU'),
	'GH' => array('id' => 84,'phone_code' => 233,'country_name' => 'Ghana','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'GHA'),
	'GI' => array('id' => 85,'phone_code' => 350,'country_name' => 'Gibraltar','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'GIB'),
	'GR' => array('id' => 86,'phone_code' => 30,'country_name' => 'Greece','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'GRC'),
	'GL' => array('id' => 87,'phone_code' => 299,'country_name' => 'Greenland','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'GRL'),
	'GD' => array('id' => 88,'phone_code' => 1473,'country_name' => 'Grenada','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'GRD'),
	'GP' => array('id' => 89,'phone_code' => 590,'country_name' => 'Guadeloupe','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'GLP'),
	'GU' => array('id' => 90,'phone_code' => 1671,'country_name' => 'Guam','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'GUM'),
	'GT' => array('id' => 91,'phone_code' => 502,'country_name' => 'Guatemala','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'GTM'),
	'GG' => array('id' => 92,'phone_code' => 44,'country_name' => 'Guernsey','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'GGY'),
	'GN' => array('id' => 93,'phone_code' => 224,'country_name' => 'Guinea','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'GIN'),
	'GW' => array('id' => 94,'phone_code' => 245,'country_name' => 'Guinea-Bissau','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'GNB'),
	'GY' => array('id' => 95,'phone_code' => 592,'country_name' => 'Guyana','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'GUY'),
	'HT' => array('id' => 96,'phone_code' => 509,'country_name' => 'Haiti','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'HTI'),
	'HM' => array('id' => 97,'phone_code' => 0,'country_name' => 'Heard Island and Mcdonald Islands','continent_code' => 'AN','continent_name' => 'Antarctica','alpha_3' => 'HMD'),
	'VA' => array('id' => 98,'phone_code' => 39,'country_name' => 'Holy See (Vatican City State)','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'VAT'),
	'HN' => array('id' => 99,'phone_code' => 504,'country_name' => 'Honduras','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'HND'),
	'HK' => array('id' => 100,'phone_code' => 852,'country_name' => 'Hong Kong','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'HKG'),
	'HU' => array('id' => 101,'phone_code' => 36,'country_name' => 'Hungary','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'HUN'),
	'IS' => array('id' => 102,'phone_code' => 354,'country_name' => 'Iceland','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'ISL'),
	'IN' => array('id' => 103,'phone_code' => 91,'country_name' => 'India','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'IND'),
	'ID' => array('id' => 104,'phone_code' => 62,'country_name' => 'Indonesia','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'IDN'),
	'IR' => array('id' => 105,'phone_code' => 98,'country_name' => 'Iran, Islamic Republic of','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'IRN'),
	'IQ' => array('id' => 106,'phone_code' => 964,'country_name' => 'Iraq','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'IRQ'),
	'IE' => array('id' => 107,'phone_code' => 353,'country_name' => 'Ireland','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'IRL'),
	'IM' => array('id' => 108,'phone_code' => 44,'country_name' => 'Isle of Man','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'IMN'),
	'IL' => array('id' => 109,'phone_code' => 972,'country_name' => 'Israel','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'ISR'),
	'IT' => array('id' => 110,'phone_code' => 39,'country_name' => 'Italy','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'ITA'),
	'JM' => array('id' => 111,'phone_code' => 1876,'country_name' => 'Jamaica','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'JAM'),
	'JP' => array('id' => 112,'phone_code' => 81,'country_name' => 'Japan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'JPN'),
	'JE' => array('id' => 113,'phone_code' => 44,'country_name' => 'Jersey','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'JEY'),
	'JO' => array('id' => 114,'phone_code' => 962,'country_name' => 'Jordan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'JOR'),
	'KZ' => array('id' => 115,'phone_code' => 7,'country_name' => 'Kazakhstan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'KAZ'),
	'KE' => array('id' => 116,'phone_code' => 254,'country_name' => 'Kenya','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'KEN'),
	'KI' => array('id' => 117,'phone_code' => 686,'country_name' => 'Kiribati','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'KIR'),
	'KP' => array('id' => 118,'phone_code' => 850,'country_name' => 'Korea, Democratic People\'s Republic of','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'PRK'),
	'KR' => array('id' => 119,'phone_code' => 82,'country_name' => 'Korea, Republic of','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'KOR'),
	'XK' => array('id' => 120,'phone_code' => 381,'country_name' => 'Kosovo','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'XKX'),
	'KW' => array('id' => 121,'phone_code' => 965,'country_name' => 'Kuwait','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'KWT'),
	'KG' => array('id' => 122,'phone_code' => 996,'country_name' => 'Kyrgyzstan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'KGZ'),
	'LA' => array('id' => 123,'phone_code' => 856,'country_name' => 'Lao People\'s Democratic Republic','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'LAO'),
	'LV' => array('id' => 124,'phone_code' => 371,'country_name' => 'Latvia','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'LVA'),
	'LB' => array('id' => 125,'phone_code' => 961,'country_name' => 'Lebanon','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'LBN'),
	'LS' => array('id' => 126,'phone_code' => 266,'country_name' => 'Lesotho','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'LSO'),
	'LR' => array('id' => 127,'phone_code' => 231,'country_name' => 'Liberia','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'LBR'),
	'LY' => array('id' => 128,'phone_code' => 218,'country_name' => 'Libyan Arab Jamahiriya','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'LBY'),
	'LI' => array('id' => 129,'phone_code' => 423,'country_name' => 'Liechtenstein','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'LIE'),
	'LT' => array('id' => 130,'phone_code' => 370,'country_name' => 'Lithuania','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'LTU'),
	'LU' => array('id' => 131,'phone_code' => 352,'country_name' => 'Luxembourg','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'LUX'),
	'MO' => array('id' => 132,'phone_code' => 853,'country_name' => 'Macao','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'MAC'),
	'MK' => array('id' => 133,'phone_code' => 389,'country_name' => 'Macedonia, the Former Yugoslav Republic of','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'MKD'),
	'MG' => array('id' => 134,'phone_code' => 261,'country_name' => 'Madagascar','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'MDG'),
	'MW' => array('id' => 135,'phone_code' => 265,'country_name' => 'Malawi','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'MWI'),
	'MY' => array('id' => 136,'phone_code' => 60,'country_name' => 'Malaysia','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'MYS'),
	'MV' => array('id' => 137,'phone_code' => 960,'country_name' => 'Maldives','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'MDV'),
	'ML' => array('id' => 138,'phone_code' => 223,'country_name' => 'Mali','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'MLI'),
	'MT' => array('id' => 139,'phone_code' => 356,'country_name' => 'Malta','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'MLT'),
	'MH' => array('id' => 140,'phone_code' => 692,'country_name' => 'Marshall Islands','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'MHL'),
	'MQ' => array('id' => 141,'phone_code' => 596,'country_name' => 'Martinique','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'MTQ'),
	'MR' => array('id' => 142,'phone_code' => 222,'country_name' => 'Mauritania','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'MRT'),
	'MU' => array('id' => 143,'phone_code' => 230,'country_name' => 'Mauritius','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'MUS'),
	'YT' => array('id' => 144,'phone_code' => 269,'country_name' => 'Mayotte','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'MYT'),
	'MX' => array('id' => 145,'phone_code' => 52,'country_name' => 'Mexico','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'MEX'),
	'FM' => array('id' => 146,'phone_code' => 691,'country_name' => 'Micronesia, Federated States of','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'FSM'),
	'MD' => array('id' => 147,'phone_code' => 373,'country_name' => 'Moldova, Republic of','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'MDA'),
	'MC' => array('id' => 148,'phone_code' => 377,'country_name' => 'Monaco','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'MCO'),
	'MN' => array('id' => 149,'phone_code' => 976,'country_name' => 'Mongolia','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'MNG'),
	'ME' => array('id' => 150,'phone_code' => 382,'country_name' => 'Montenegro','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'MNE'),
	'MS' => array('id' => 151,'phone_code' => 1664,'country_name' => 'Montserrat','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'MSR'),
	'MA' => array('id' => 152,'phone_code' => 212,'country_name' => 'Morocco','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'MAR'),
	'MZ' => array('id' => 153,'phone_code' => 258,'country_name' => 'Mozambique','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'MOZ'),
	'MM' => array('id' => 154,'phone_code' => 95,'country_name' => 'Myanmar','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'MMR'),
	'NA' => array('id' => 155,'phone_code' => 264,'country_name' => 'Namibia','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'NAM'),
	'NR' => array('id' => 156,'phone_code' => 674,'country_name' => 'Nauru','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'NRU'),
	'NP' => array('id' => 157,'phone_code' => 977,'country_name' => 'Nepal','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'NPL'),
	'NL' => array('id' => 158,'phone_code' => 31,'country_name' => 'Netherlands','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'NLD'),
	'AN' => array('id' => 159,'phone_code' => 599,'country_name' => 'Netherlands Antilles','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'ANT'),
	'NC' => array('id' => 160,'phone_code' => 687,'country_name' => 'New Caledonia','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'NCL'),
	'NZ' => array('id' => 161,'phone_code' => 64,'country_name' => 'New Zealand','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'NZL'),
	'NI' => array('id' => 162,'phone_code' => 505,'country_name' => 'Nicaragua','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'NIC'),
	'NE' => array('id' => 163,'phone_code' => 227,'country_name' => 'Niger','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'NER'),
	'NG' => array('id' => 164,'phone_code' => 234,'country_name' => 'Nigeria','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'NGA'),
	'NU' => array('id' => 165,'phone_code' => 683,'country_name' => 'Niue','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'NIU'),
	'NF' => array('id' => 166,'phone_code' => 672,'country_name' => 'Norfolk Island','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'NFK'),
	'MP' => array('id' => 167,'phone_code' => 1670,'country_name' => 'Northern Mariana Islands','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'MNP'),
	'NO' => array('id' => 168,'phone_code' => 47,'country_name' => 'Norway','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'NOR'),
	'OM' => array('id' => 169,'phone_code' => 968,'country_name' => 'Oman','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'OMN'),
	'PK' => array('id' => 170,'phone_code' => 92,'country_name' => 'Pakistan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'PAK'),
	'PW' => array('id' => 171,'phone_code' => 680,'country_name' => 'Palau','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'PLW'),
	'PS' => array('id' => 172,'phone_code' => 970,'country_name' => 'Palestinian Territory, Occupied','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'PSE'),
	'PA' => array('id' => 173,'phone_code' => 507,'country_name' => 'Panama','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'PAN'),
	'PG' => array('id' => 174,'phone_code' => 675,'country_name' => 'Papua New Guinea','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'PNG'),
	'PY' => array('id' => 175,'phone_code' => 595,'country_name' => 'Paraguay','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'PRY'),
	'PE' => array('id' => 176,'phone_code' => 51,'country_name' => 'Peru','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'PER'),
	'PH' => array('id' => 177,'phone_code' => 63,'country_name' => 'Philippines','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'PHL'),
	'PN' => array('id' => 178,'phone_code' => 64,'country_name' => 'Pitcairn','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'PCN'),
	'PL' => array('id' => 179,'phone_code' => 48,'country_name' => 'Poland','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'POL'),
	'PT' => array('id' => 180,'phone_code' => 351,'country_name' => 'Portugal','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'PRT'),
	'PR' => array('id' => 181,'phone_code' => 1787,'country_name' => 'Puerto Rico','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'PRI'),
	'QA' => array('id' => 182,'phone_code' => 974,'country_name' => 'Qatar','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'QAT'),
	'RE' => array('id' => 183,'phone_code' => 262,'country_name' => 'Reunion','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'REU'),
	'RO' => array('id' => 184,'phone_code' => 40,'country_name' => 'Romania','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'ROM'),
	'RU' => array('id' => 185,'phone_code' => 70,'country_name' => 'Russian Federation','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'RUS'),
	'RW' => array('id' => 186,'phone_code' => 250,'country_name' => 'Rwanda','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'RWA'),
	'BL' => array('id' => 187,'phone_code' => 590,'country_name' => 'Saint Barthelemy','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'BLM'),
	'SH' => array('id' => 188,'phone_code' => 290,'country_name' => 'Saint Helena','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'SHN'),
	'KN' => array('id' => 189,'phone_code' => 1869,'country_name' => 'Saint Kitts and Nevis','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'KNA'),
	'LC' => array('id' => 190,'phone_code' => 1758,'country_name' => 'Saint Lucia','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'LCA'),
	'MF' => array('id' => 191,'phone_code' => 590,'country_name' => 'Saint Martin','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'MAF'),
	'PM' => array('id' => 192,'phone_code' => 508,'country_name' => 'Saint Pierre and Miquelon','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'SPM'),
	'VC' => array('id' => 193,'phone_code' => 1784,'country_name' => 'Saint Vincent and the Grenadines','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'VCT'),
	'WS' => array('id' => 194,'phone_code' => 684,'country_name' => 'Samoa','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'WSM'),
	'SM' => array('id' => 195,'phone_code' => 378,'country_name' => 'San Marino','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'SMR'),
	'ST' => array('id' => 196,'phone_code' => 239,'country_name' => 'Sao Tome and Principe','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'STP'),
	'SA' => array('id' => 197,'phone_code' => 966,'country_name' => 'Saudi Arabia','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'SAU'),
	'SN' => array('id' => 198,'phone_code' => 221,'country_name' => 'Senegal','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'SEN'),
	'RS' => array('id' => 199,'phone_code' => 381,'country_name' => 'Serbia','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'SRB'),
	'CS' => array('id' => 200,'phone_code' => 381,'country_name' => 'Serbia and Montenegro','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'SCG'),
	'SC' => array('id' => 201,'phone_code' => 248,'country_name' => 'Seychelles','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'SYC'),
	'SL' => array('id' => 202,'phone_code' => 232,'country_name' => 'Sierra Leone','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'SLE'),
	'SG' => array('id' => 203,'phone_code' => 65,'country_name' => 'Singapore','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'SGP'),
	'SX' => array('id' => 204,'phone_code' => 1,'country_name' => 'Sint Maarten','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'SXM'),
	'SK' => array('id' => 205,'phone_code' => 421,'country_name' => 'Slovakia','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'SVK'),
	'SI' => array('id' => 206,'phone_code' => 386,'country_name' => 'Slovenia','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'SVN'),
	'SB' => array('id' => 207,'phone_code' => 677,'country_name' => 'Solomon Islands','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'SLB'),
	'SO' => array('id' => 208,'phone_code' => 252,'country_name' => 'Somalia','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'SOM'),
	'ZA' => array('id' => 209,'phone_code' => 27,'country_name' => 'South Africa','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'ZAF'),
	'GS' => array('id' => 210,'phone_code' => 500,'country_name' => 'South Georgia and the South Sandwich Islands','continent_code' => 'AN','continent_name' => 'Antarctica','alpha_3' => 'SGS'),
	'SS' => array('id' => 211,'phone_code' => 211,'country_name' => 'South Sudan','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'SSD'),
	'ES' => array('id' => 212,'phone_code' => 34,'country_name' => 'Spain','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'ESP'),
	'LK' => array('id' => 213,'phone_code' => 94,'country_name' => 'Sri Lanka','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'LKA'),
	'SD' => array('id' => 214,'phone_code' => 249,'country_name' => 'Sudan','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'SDN'),
	'SR' => array('id' => 215,'phone_code' => 597,'country_name' => 'Suriname','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'SUR'),
	'SJ' => array('id' => 216,'phone_code' => 47,'country_name' => 'Svalbard and Jan Mayen','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'SJM'),
	'SZ' => array('id' => 217,'phone_code' => 268,'country_name' => 'Swaziland','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'SWZ'),
	'SE' => array('id' => 218,'phone_code' => 46,'country_name' => 'Sweden','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'SWE'),
	'CH' => array('id' => 219,'phone_code' => 41,'country_name' => 'Switzerland','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'CHE'),
	'SY' => array('id' => 220,'phone_code' => 963,'country_name' => 'Syrian Arab Republic','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'SYR'),
	'TW' => array('id' => 221,'phone_code' => 886,'country_name' => 'Taiwan, Province of China','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'TWN'),
	'TJ' => array('id' => 222,'phone_code' => 992,'country_name' => 'Tajikistan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'TJK'),
	'TZ' => array('id' => 223,'phone_code' => 255,'country_name' => 'Tanzania, United Republic of','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'TZA'),
	'TH' => array('id' => 224,'phone_code' => 66,'country_name' => 'Thailand','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'THA'),
	'TL' => array('id' => 225,'phone_code' => 670,'country_name' => 'Timor-Leste','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'TLS'),
	'TG' => array('id' => 226,'phone_code' => 228,'country_name' => 'Togo','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'TGO'),
	'TK' => array('id' => 227,'phone_code' => 690,'country_name' => 'Tokelau','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'TKL'),
	'TO' => array('id' => 228,'phone_code' => 676,'country_name' => 'Tonga','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'TON'),
	'TT' => array('id' => 229,'phone_code' => 1868,'country_name' => 'Trinidad and Tobago','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'TTO'),
	'TN' => array('id' => 230,'phone_code' => 216,'country_name' => 'Tunisia','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'TUN'),
	'TR' => array('id' => 231,'phone_code' => 90,'country_name' => 'Turkey','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'TUR'),
	'TM' => array('id' => 232,'phone_code' => 7370,'country_name' => 'Turkmenistan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'TKM'),
	'TC' => array('id' => 233,'phone_code' => 1649,'country_name' => 'Turks and Caicos Islands','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'TCA'),
	'TV' => array('id' => 234,'phone_code' => 688,'country_name' => 'Tuvalu','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'TUV'),
	'UG' => array('id' => 235,'phone_code' => 256,'country_name' => 'Uganda','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'UGA'),
	'UA' => array('id' => 236,'phone_code' => 380,'country_name' => 'Ukraine','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'UKR'),
	'AE' => array('id' => 237,'phone_code' => 971,'country_name' => 'United Arab Emirates','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'ARE'),
	'GB' => array('id' => 238,'phone_code' => 44,'country_name' => 'United Kingdom','continent_code' => 'EU','continent_name' => 'Europe','alpha_3' => 'GBR'),
	'US' => array('id' => 239,'phone_code' => 1,'country_name' => 'United States','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'USA'),
	'UM' => array('id' => 240,'phone_code' => 1,'country_name' => 'United States Minor Outlying Islands','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'UMI'),
	'UY' => array('id' => 241,'phone_code' => 598,'country_name' => 'Uruguay','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'URY'),
	'UZ' => array('id' => 242,'phone_code' => 998,'country_name' => 'Uzbekistan','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'UZB'),
	'VU' => array('id' => 243,'phone_code' => 678,'country_name' => 'Vanuatu','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'VUT'),
	'VE' => array('id' => 244,'phone_code' => 58,'country_name' => 'Venezuela','continent_code' => 'SA','continent_name' => 'South America','alpha_3' => 'VEN'),
	'VN' => array('id' => 245,'phone_code' => 84,'country_name' => 'Viet Nam','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'VNM'),
	'VG' => array('id' => 246,'phone_code' => 1284,'country_name' => 'Virgin Islands, British','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'VGB'),
	'VI' => array('id' => 247,'phone_code' => 1340,'country_name' => 'Virgin Islands, U.s.','continent_code' => 'NA','continent_name' => 'North America','alpha_3' => 'VIR'),
	'WF' => array('id' => 248,'phone_code' => 681,'country_name' => 'Wallis and Futuna','continent_code' => 'OC','continent_name' => 'Oceania','alpha_3' => 'WLF'),
	'EH' => array('id' => 249,'phone_code' => 212,'country_name' => 'Western Sahara','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'ESH'),
	'YE' => array('id' => 250,'phone_code' => 967,'country_name' => 'Yemen','continent_code' => 'AS','continent_name' => 'Asia','alpha_3' => 'YEM'),
	'ZM' => array('id' => 251,'phone_code' => 260,'country_name' => 'Zambia','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'ZMB'),
	'ZW' => array('id' => 252,'phone_code' => 263,'country_name' => 'Zimbabwe','continent_code' => 'AF','continent_name' => 'Africa','alpha_3' => 'ZWE')
);
?>